- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleShadowling
  name: Shadowling Role
  components:
  - type: MindRole
    antagPrototype: Shadowling
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: ShadowlingRole
  # MAID BEGIN adaptive scores
  - type: AdaptiveScoreStatic
    combatScore: 0
    chaosScore: 0
    conditions:
    - !type:Controlled
    - !type:Alive
  # MAID END adaptive scores

- type: entity
  parent: MindRoleShadowling
  id: MindRoleThrall
  name: Thrall Role
  components:
  - type: MindRole
    antagPrototype: Thrall
