using System.Text.RegularExpressions;
using Content.Client.UserInterface.Controls;
using Content.Shared._Maid.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Maid.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class ATMWindow : FancyWindow
{
    public const int PinLength = 4;

    private static readonly Regex NotDigits = new("[^0-9]");

    public event Action<int, int>? OnWithdrawAttempt;

    public ATMWindow()
    {
        RobustXamlLoader.Load(this);

        WithdrawButton.OnPressed += _ =>
        {
            if (!int.TryParse(PinLineEdit.Text, out var pin))
                return;

            OnWithdrawAttempt?.Invoke(WithdrawSlider.Value, pin);
        };

        PinLineEdit.OnTextChanged += _ =>
        {
            var pin = NotDigits.Replace(PinLineEdit.Text, string.Empty);
            if (pin.Length > PinLength)
                pin = pin[..PinLength];

            if (pin != PinLineEdit.Text)
                PinLineEdit.Text = pin;

            WithdrawButton.Disabled = pin.Length != PinLength;
        };
    }

    public void UpdateState(ATMBuiState state)
    {
        StatusLabel.Text = state.InfoMessage;
        BalanceLabel.Visible = state.HasCard;
        BalanceLabel.Text = Loc.GetString("atm-ui-balance", ("balance", state.AccountBalance));

        var canWithdraw = state.HasCard && state.AccountBalance > 0;
        Divider.Visible = canWithdraw;
        WithdrawSlider.Visible = canWithdraw;
        PinLineEdit.Visible = canWithdraw;
        WithdrawButton.Visible = canWithdraw;

        if (!canWithdraw)
            return;

        WithdrawSlider.MaxValue = state.AccountBalance;
        WithdrawSlider.Value = Math.Min(WithdrawSlider.Value, state.AccountBalance);
    }
}
