using System.Text.RegularExpressions;
using Content.Client.Message;
using Content.Shared._Maid.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Maid.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class BankUiFragment : BoxContainer
{
    private const int AccountLength = 6;
    private const int PinLength = 4;

    private static readonly Regex NotDigits = new("[^0-9]");

    public event Action<int, int>? OnLinkAttempt;

    private bool _accountLinkActive;

    public BankUiFragment()
    {
        RobustXamlLoader.Load(this);

        AccountLinkButton.OnPressed += _ =>
        {
            _accountLinkActive = true;
            AccountLinkResultLabel.Visible = false;
            UpdateAccountLinkUi();
        };

        LinkCancelButton.OnPressed += _ =>
        {
            _accountLinkActive = false;
            UpdateAccountLinkUi();
        };

        AccountLineEdit.OnTextChanged += _ => ValidateLineEdit(AccountLineEdit, AccountLength);
        PinLineEdit.OnTextChanged += _ => ValidateLineEdit(PinLineEdit, PinLength);

        LinkConfirmButton.OnPressed += _ =>
        {
            if (!int.TryParse(AccountLineEdit.Text, out var accountId) || !int.TryParse(PinLineEdit.Text, out var pin))
                return;

            AccountLinkResultLabel.Visible = true;
            _accountLinkActive = false;
            OnLinkAttempt?.Invoke(accountId, pin);
        };
    }

    public void UpdateState(BankCartridgeUiState state)
    {
        var accountLinked = state.AccountId != null;

        AccountLinkMessageLabel.SetMarkup(state.AccountLinkMessage);
        AccountLinkResultLabel.SetMarkup(state.AccountLinkResult);

        LinkedAccount.Visible = accountLinked;
        NoLinkedAccountLabel.Visible = !accountLinked;

        if (accountLinked)
        {
            LinkedAccountNumberLabel.SetMarkup(Loc.GetString("bank-program-ui-account-number-text",
                ("account", state.AccountId!.Value)));
            LinkedAccountNameLabel.SetMarkup(Loc.GetString("bank-program-ui-account-owner-text",
                ("owner", state.OwnerName)));
            LinkedAccountBalanceLabel.SetMarkup(Loc.GetString("atm-ui-balance", ("balance", state.Balance)));
        }
        else
        {
            NoLinkedAccountLabel.SetMarkup(Loc.GetString("bank-program-ui-no-account"));
        }

        UpdateAccountLinkUi();
    }

    private void UpdateAccountLinkUi()
    {
        AccountLinkButton.Visible = !_accountLinkActive;
        AccountLink.Visible = _accountLinkActive;
    }

    private void ValidateLineEdit(LineEdit lineEdit, int length)
    {
        var text = NotDigits.Replace(lineEdit.Text, string.Empty);
        if (text.Length > length)
            text = text[..length];

        if (text != lineEdit.Text)
            lineEdit.Text = text;

        LinkConfirmButton.Disabled = AccountLineEdit.Text.Length != AccountLength || PinLineEdit.Text.Length != PinLength;
    }
}
