using System.Text.RegularExpressions;
using Content.Client.UserInterface.Controls;
using Content.Shared._Maid.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Maid.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EftposWindow : FancyWindow
{
    private static readonly Regex NotDigits = new("[^0-9]");

    public event Action<int>? OnCardButtonPressed;

    public EftposWindow()
    {
        RobustXamlLoader.Load(this);

        AmountLineEdit.OnTextChanged += _ =>
        {
            var amount = NotDigits.Replace(AmountLineEdit.Text, string.Empty);
            if (amount != AmountLineEdit.Text)
                AmountLineEdit.Text = amount;
        };

        CardButton.OnPressed += _ =>
        {
            int.TryParse(AmountLineEdit.Text, out var amount);
            OnCardButtonPressed?.Invoke(amount);
        };
    }

    public void UpdateState(EftposBuiState state)
    {
        AmountLineEdit.Text = state.Amount == 0 ? string.Empty : state.Amount.ToString();
        AmountLineEdit.Editable = !state.Locked;

        CardButton.Text = Loc.GetString(state.Locked ? "eftpos-ui-card-unlock-text" : "eftpos-ui-card-lock-text");
        CardButton.ToolTip = Loc.GetString(state.Locked ? "eftpos-ui-card-unlock-desc" : "eftpos-ui-card-lock-desc");

        AccountLabel.Text = state.Owner == string.Empty
            ? string.Empty
            : Loc.GetString("eftpos-ui-account-text", ("owner", state.Owner));
    }
}
